import { createContext, useContext } from 'react';

// Catálogo de recursos. Es el ÚNICO contenido del sitio y refleja exactamente
// la estructura de carpetas del Drive (misma distribución). Se actualiza solo
// aquí, en código, cuando se agrega o reorganiza material en el Drive.
//
//   Cuentos infantiles (15) · Material para padres (11) · Materiales para psicólogos y afines (18) = 44
//
const R = './Material terremoto niños';

const resources = [
  // ===== Cuentos infantiles · Sobre terremotos =====
  { id: 1, category: 'Cuentos infantiles', subcategory: 'Sobre terremotos', type: 'PDF', title: 'Ana y el Terremoto', description: 'Cuento que acompaña a las niñas y niños a entender y calmar el miedo después de un temblor.', url: `${R}/Cuentos infantiles/Sobre terremotos/Ana-y-el-terremoto.pdf` },
  { id: 2, category: 'Cuentos infantiles', subcategory: 'Sobre terremotos', type: 'PDF', title: 'Bruno y Violeta Sobreviven al Terremoto', description: 'Cuento ilustrado que ayuda a los más pequeños a comprender qué pasó y a sentirse acompañados.', url: `${R}/Cuentos infantiles/Sobre terremotos/Bruno y Violeta sobreviven al terremoto.pdf` },
  { id: 3, category: 'Cuentos infantiles', subcategory: 'Sobre terremotos', type: 'PDF', title: 'Cuando la Tierra se Movió (México)', description: 'Cuento ilustrado para explicarles a las niñas y niños qué es un sismo y por qué ocurre.', url: `${R}/Cuentos infantiles/Sobre terremotos/CUANDO-LA-TIERRA-SE-MOVIO-MEXICO.pdf` },
  { id: 4, category: 'Cuentos infantiles', subcategory: 'Sobre terremotos', type: 'PDF', title: 'Cuando la Tierra se Mueve, Tus Manos me Sostienen', description: 'Cuento sobre la contención y el cariño de los cuidadores como refugio seguro ante el miedo.', url: `${R}/Cuentos infantiles/Sobre terremotos/CUENTO CUANDO LA TIERRA SE MUEVE, TUS MANOS ME SOSTIENEN (A4).pdf` },
  { id: 5, category: 'Cuentos infantiles', subcategory: 'Sobre terremotos', type: 'PDF', title: 'Cuando la Tierra se Movió', description: 'Cuento ilustrado centrado en el impacto emocional de los sismos en la infancia.', url: `${R}/Cuentos infantiles/Sobre terremotos/Cuando la tierra se movió.pdf` },
  { id: 6, category: 'Cuentos infantiles', subcategory: 'Sobre terremotos', type: 'PDF', title: 'Érase una Vez unos Valientes', description: 'Cuento sobre la valentía y la esperanza compartida para sobrellevar un desastre.', url: `${R}/Cuentos infantiles/Sobre terremotos/Cuento_erase_una_vez_unos_valientes.pdf` },
  { id: 7, category: 'Cuentos infantiles', subcategory: 'Sobre terremotos', type: 'PDF', title: 'El Día que Todo se Movió', description: 'Cuento para acompañar a las niñas y niños a comprender y nombrar lo que sintieron durante el sismo.', url: `${R}/Cuentos infantiles/Sobre terremotos/El día que todo se movió.pdf` },
  { id: 8, category: 'Cuentos infantiles', subcategory: 'Sobre terremotos', type: 'PDF', title: 'LUMA y el Terremoto', description: 'Cuento ilustrado que acompaña a la niñez a procesar la experiencia de un terremoto.', url: `${R}/Cuentos infantiles/Sobre terremotos/LUMA - terremoto.pdf` },
  { id: 9, category: 'Cuentos infantiles', subcategory: 'Sobre terremotos', type: 'PDF', title: 'Plaza Sésamo: Contención Emocional', description: 'Material oficial de Plaza Sésamo para acompañar y contener emocionalmente a los más pequeños.', url: `${R}/Cuentos infantiles/Sobre terremotos/Material Plaza Sesamo contención emocional.pdf` },
  { id: 10, category: 'Cuentos infantiles', subcategory: 'Sobre terremotos', type: 'PDF', title: 'Mi Miedo, Mi Guardián Personal', description: 'Lectura para resignificar el miedo como una herramienta natural de protección.', url: `${R}/Cuentos infantiles/Sobre terremotos/Mi miedo mi guardián personal.pdf` },
  { id: 11, category: 'Cuentos infantiles', subcategory: 'Sobre terremotos', type: 'Actividad Práctica', title: 'Respira', description: 'Cuento-guía con ejercicios de respiración para recuperar la calma.', url: `${R}/Cuentos infantiles/Sobre terremotos/Respira_compressed.pdf` },
  { id: 12, category: 'Cuentos infantiles', subcategory: 'Sobre terremotos', type: 'PDF', title: 'Trinka y Sam: El Día que la Tierra Tembló', description: 'Cuento de Trinka y Sam para ayudar a las niñas y niños a procesar desastres naturales.', url: `${R}/Cuentos infantiles/Sobre terremotos/trinka_sam_the_day_the_earth_shook_sp.pdf` },

  // ===== Cuentos infantiles · Sobre el duelo y la muerte =====
  { id: 13, category: 'Cuentos infantiles', subcategory: 'Sobre el duelo y la muerte', type: 'PDF', title: 'El Tejedor Invisible del Corazón', description: 'Cuento para trabajar las emociones, los vínculos y la esperanza tras una pérdida.', url: `${R}/Cuentos infantiles/Sobre el duelo y la muerte/El tejedor invisible del corazón.pdf` },
  { id: 14, category: 'Cuentos infantiles', subcategory: 'Sobre el duelo y la muerte', type: 'PDF', title: 'El Árbol de los Recuerdos', description: 'Cuento para acompañar el duelo honrando los recuerdos de quienes ya no están.', url: `${R}/Cuentos infantiles/Sobre el duelo y la muerte/CUENTO-El-arbol-de-los-recuerdos.pdf` },
  { id: 15, category: 'Cuentos infantiles', subcategory: 'Sobre el duelo y la muerte', type: 'PDF', title: 'No es Fácil, Pequeña Ardilla', description: 'Cuento para acompañar a las niñas y niños en el duelo y la expresión de la tristeza.', url: `${R}/Cuentos infantiles/Sobre el duelo y la muerte/CUENTO-No-es-facil-pequena-ardilla.pdf` },

  // ===== Material para padres · Sobre terremotos =====
  { id: 16, category: 'Material para padres', subcategory: 'Sobre terremotos', type: 'Guía Escrita', title: 'Respondiendo a las Necesidades Emocionales de los Niños', description: 'Guía de la AAP y CHLA para padres y cuidadores tras una emergencia.', url: `${R}/Material para padres/Sobre terremotos/CHLA-AAP-Responding-to-Childrens-Emotional-Needs-Spanish_0.pdf` },
  { id: 17, category: 'Material para padres', subcategory: 'Sobre terremotos', type: 'PDF', title: 'Reacciones a Eventos Traumáticos según la Edad', description: 'De la NCTSN: cómo responden los menores ante el trauma según su etapa de desarrollo.', url: `${R}/Material para padres/Sobre terremotos/NCTSN age_related_reactions_to_traumatic_events_sp.pdf` },
  { id: 18, category: 'Material para padres', subcategory: 'Sobre terremotos', type: 'Actividad Práctica', title: 'Actividades Simples para Niños y Adolescentes', description: 'Dinámicas prácticas de la NCTSN para hacer en casa y reducir la tensión y el estrés.', url: `${R}/Material para padres/Sobre terremotos/NCTSN simple_activities_for_children_and_adolescents_spanish.pdf` },
  { id: 19, category: 'Material para padres', subcategory: 'Sobre terremotos', type: 'PDF', title: '12 Conceptos Básicos sobre el Estrés Traumático', description: 'Marco de la NCTSN para entender el comportamiento de la familia ante el trauma.', url: `${R}/Material para padres/Sobre terremotos/NCTSN the_12_core_concepts_for_understanding_traumatic_stress_responses_in_children_and_families_sp.pdf` },
  { id: 20, category: 'Material para padres', subcategory: 'Sobre terremotos', type: 'Guía Escrita', title: 'Guía Familiar ante Sismos y Maremotos', description: 'De UNICEF: recomendaciones de preparación y respuesta para toda la familia.', url: `${R}/Material para padres/Sobre terremotos/UNICEF guia-familiar-sismos-maremotos.pdf` },
  { id: 21, category: 'Material para padres', subcategory: 'Sobre terremotos', type: 'PDF', title: 'Ayudando a los Padres a Sobrellevar el Desastre (en inglés)', description: 'Folleto de CHLA y CDC con recursos básicos de manejo del estrés. Documento en inglés.', url: `${R}/Material para padres/Sobre terremotos/inglés CHLA-CDC-Helping-Parents-Cope-with-Disaster-English.pdf` },

  // ===== Material para padres · Sobre muerte y duelo =====
  { id: 22, category: 'Material para padres', subcategory: 'Sobre muerte y duelo', type: 'Guía Escrita', title: 'Duelo Traumático en la Infancia (Resumen)', description: 'Conceptos fundamentales sobre el duelo en la edad pediátrica tras un desastre.', url: `${R}/Material para padres/Sobre muerte y duelo/brief_information_on_childhood_traumatic_grief_sp.pdf` },
  { id: 23, category: 'Material para padres', subcategory: 'Sobre muerte y duelo', type: 'PDF', title: 'Duelo Traumático: Guía Completa para Padres', description: 'Guía extendida con recomendaciones para acompañar a los hijos en el duelo.', url: `${R}/Material para padres/Sobre muerte y duelo/childhood_traumatic_grief_materials_parents_sp.pdf` },
  { id: 24, category: 'Material para padres', subcategory: 'Sobre muerte y duelo', type: 'Guía Escrita', title: 'Cómo Acompañar ante una Muerte no Confirmada', description: 'Apoyo para familias con menores en situaciones de personas desaparecidas.', url: `${R}/Material para padres/Sobre muerte y duelo/coping-with-unconfirmed-death-for-forcibly-displaced-children-and-families-caregivers-sp_0.pdf` },
  { id: 25, category: 'Material para padres', subcategory: 'Sobre muerte y duelo', type: 'PDF', title: 'Ayudando a Adolescentes con Duelo Traumático', description: 'Estrategias específicas para acompañar a jóvenes que atraviesan un duelo.', url: `${R}/Material para padres/Sobre muerte y duelo/helping-teens-with-traumatic-grief-for-caregivers-sp.pdf` },
  { id: 26, category: 'Material para padres', subcategory: 'Sobre muerte y duelo', type: 'Guía Escrita', title: 'Plan para Manejar los Recuerdos del Evento', description: 'Pasos prácticos para enfrentar los detonantes y los recuerdos intrusivos.', url: `${R}/Material para padres/Sobre muerte y duelo/making_a_plan_dealing_with_things_that_remind_you_what_happened_sp.pdf` },

  // ===== Materiales para psicólogos y afines · Culpa del sobreviviente =====
  { id: 27, category: 'Materiales para psicólogos y afines', subcategory: 'Culpa del sobreviviente', type: 'Artículo', title: 'Culpa del Superviviente y TEPT (Terremoto Turquía-Siria)', description: 'Artículo científico sobre la culpa del superviviente como mediadora del TEPT. En inglés.', url: `${R}/Materiales para psicólogos y afines/Culpa del sobreviviente/Articulo cientifico -Survivor Guilt as a Mediator Between Post-Traumatic Stress Disorder and Pessimism Schema After Türkiye-Syria Earthquake.pdf` },
  { id: 28, category: 'Materiales para psicólogos y afines', subcategory: 'Culpa del sobreviviente', type: 'Artículo', title: 'La Culpa del Superviviente: Un Enfoque Cognitivo', description: 'Artículo científico sobre la comprensión cognitiva de la culpa del superviviente. En inglés.', url: `${R}/Materiales para psicólogos y afines/Culpa del sobreviviente/Articulo científico Survivor_Guilt_A_Cognitive_Approach.pdf` },
  { id: 29, category: 'Materiales para psicólogos y afines', subcategory: 'Culpa del sobreviviente', type: 'Artículo', title: 'La Culpa del Superviviente: Aproximación Cognitiva', description: 'Artículo científico sobre la culpa del superviviente desde un enfoque cognitivo. En inglés.', url: `${R}/Materiales para psicólogos y afines/Culpa del sobreviviente/Artículo cientifico-Survivor Guilt- A Cognitive Approach.pdf` },
  { id: 30, category: 'Materiales para psicólogos y afines', subcategory: 'Culpa del sobreviviente', type: 'PDF', title: 'Culpa del Superviviente — Guía para Víctimas (MADD)', description: 'Material de MADD sobre la culpa del superviviente y el proceso de duelo. En inglés.', url: `${R}/Materiales para psicólogos y afines/Culpa del sobreviviente/MADD victim-survivor-survivor-guilt.pdf` },

  // ===== Materiales para psicólogos y afines · Material sobre la muerte =====
  { id: 31, category: 'Materiales para psicólogos y afines', subcategory: 'Material sobre la muerte', type: 'Artículo', title: 'Prevención del TEPT en Supervivientes', description: 'Artículo científico sobre la prevención del trastorno de estrés postraumático en supervivientes.', url: `${R}/Materiales para psicólogos y afines/Material sobre la muerte/Articulos cientifico-Prevención de trastorno de estrés posttraumático en supervivientes.pdf` },
  { id: 32, category: 'Materiales para psicólogos y afines', subcategory: 'Material sobre la muerte', type: 'Guía Escrita', title: 'Cómo Hablar con los Niños sobre las Tragedias', description: 'Recomendaciones de HealthyChildren.org (AAP) para hablar de tragedias y malas noticias.', url: `${R}/Materiales para psicólogos y afines/Material sobre la muerte/Cómo hablar con los niños sobre las tragedias y otras malas noticias - HealthyChildren.org.pdf` },
  { id: 33, category: 'Materiales para psicólogos y afines', subcategory: 'Material sobre la muerte', type: 'Guía Escrita', title: 'Cómo Hablar de la Muerte a los Niños', description: 'Guía de la Asociación Mexicana de Tanatología para acompañar a la niñez ante la muerte.', url: `${R}/Materiales para psicólogos y afines/Material sobre la muerte/Cómo hablar de la muerte a los niños ASOCIACION MEXICANA DE TANATOLOGIA A.C..pdf` },
  { id: 34, category: 'Materiales para psicólogos y afines', subcategory: 'Material sobre la muerte', type: 'Guía Escrita', title: 'Orientación para Hablar de la Muerte y los Servicios Fúnebres', description: 'Guía de la NCTSN para adultos que acompañan a niñas y niños en duelo.', url: `${R}/Materiales para psicólogos y afines/Material sobre la muerte/NCTSN guiding_adults_in_talking_about_death_and_services.pdf` },
  { id: 35, category: 'Materiales para psicólogos y afines', subcategory: 'Material sobre la muerte', type: 'Guía Escrita', title: 'Sobreviviendo al Duelo Traumático, Vol. 1', description: 'Guía del Australian Centre for Grief and Bereavement. En inglés.', url: `${R}/Materiales para psicólogos y afines/Material sobre la muerte/Surviving-Traumatic-Grief-vol1 Australian Centre for Grief and Bereavement.pdf` },

  // ===== Materiales para psicólogos y afines · Primeros Auxilios Psicológicos y atención psicosocial =====
  { id: 36, category: 'Materiales para psicólogos y afines', subcategory: 'Primeros Auxilios Psicológicos', type: 'Guía Escrita', title: 'Fichas Psicológicas de Intervención', description: 'Fichas de trabajo para apoyar la intervención y la contención psicológica.', url: `${R}/Materiales para psicólogos y afines/Primeros Auxilios Psicológicos y atención psicosocial/Fichas Psicológicas.pdf` },
  { id: 37, category: 'Materiales para psicólogos y afines', subcategory: 'Primeros Auxilios Psicológicos', type: 'Guía Escrita', title: 'Guía de Primeros Auxilios Psicológicos (Más Paz Mental)', description: 'Manual de primeros auxilios psicológicos del Equipo Más Paz Mental.', url: `${R}/Materiales para psicólogos y afines/Primeros Auxilios Psicológicos y atención psicosocial/Guia Primeros Auxilios Psicologicos Equipo Más Paz Mental.pdf` },
  { id: 38, category: 'Materiales para psicólogos y afines', subcategory: 'Primeros Auxilios Psicológicos', type: 'PDF', title: 'Guía de Apoyo Psicosocial en Emergencias (Save the Children)', description: 'Manual de Save the Children para el apoyo psicosocial a la niñez en situaciones de emergencia.', url: `${R}/Materiales para psicólogos y afines/Primeros Auxilios Psicológicos y atención psicosocial/Guia-de-apoyo-psicosocial-en-situaciones-de-emergencia-Save-the-Children.pdf` },
  { id: 39, category: 'Materiales para psicólogos y afines', subcategory: 'Primeros Auxilios Psicológicos', type: 'Guía Escrita', title: 'Guía de Apoyo Psicosocial en Emergencias y Desastres', description: 'Manual de apoyo psicosocial para la respuesta en emergencias y desastres.', url: `${R}/Materiales para psicólogos y afines/Primeros Auxilios Psicológicos y atención psicosocial/Guía Apoyo psicosocial emergencias y desastres.pdf` },
  { id: 40, category: 'Materiales para psicólogos y afines', subcategory: 'Primeros Auxilios Psicológicos', type: 'PDF', title: 'Manual de PAP para Población Migrante (FUNDAPEM)', description: 'Guía de primeros auxilios psicológicos con enfoque en población migrante y desplazada.', url: `${R}/Materiales para psicólogos y afines/Primeros Auxilios Psicológicos y atención psicosocial/MANUAL-PRIMEROS-AUXILIOS-PSICOLOGICOS-POBLACION-MIGRANTE FUNDAPEM.pdf` },
  { id: 41, category: 'Materiales para psicólogos y afines', subcategory: 'Primeros Auxilios Psicológicos', type: 'PDF', title: 'Manual ABCDE para la Aplicación de PAP (PUC Chile · CIGIDEN)', description: 'Método ABCDE para aplicar primeros auxilios psicológicos en crisis individuales y colectivas.', url: `${R}/Materiales para psicólogos y afines/Primeros Auxilios Psicológicos y atención psicosocial/Manual ACBDE para la aplicación de PAP PUC Chile y CIGIDEN.pdf` },
  { id: 42, category: 'Materiales para psicólogos y afines', subcategory: 'Primeros Auxilios Psicológicos', type: 'Guía Escrita', title: 'Guía Práctica de Salud Mental en Desastres (OPS)', description: 'Guía de la OPS/OMS para la atención de la salud mental en situaciones de desastres.', url: `${R}/Materiales para psicólogos y afines/Primeros Auxilios Psicológicos y atención psicosocial/OPS Guía práctica de salud mental en desastres.pdf` },
  { id: 43, category: 'Materiales para psicólogos y afines', subcategory: 'Primeros Auxilios Psicológicos', type: 'Guía Escrita', title: 'Protocolo ACERCARSE de Primeros Auxilios Psicológicos', description: 'Técnica estructurada de contención y estabilización emocional (Universidad de Madrid).', url: `${R}/Materiales para psicólogos y afines/Primeros Auxilios Psicológicos y atención psicosocial/PRIMEROS AUXILIOS PSICOLÓGICOS PROTOCOLO ACERCARSE Universidad de Madrid.pdf` },
  { id: 44, category: 'Materiales para psicólogos y afines', subcategory: 'Primeros Auxilios Psicológicos', type: 'Guía Escrita', title: 'Primeros Auxilios Psicológicos (Ser en Calma)', description: 'Guía breve de primeros auxilios psicológicos para la contención inicial.', url: `${R}/Materiales para psicólogos y afines/Primeros Auxilios Psicológicos y atención psicosocial/Primeros Auxilios Psicológicos — Ser en Calma.pdf` }
];

const AppContext = createContext();

export const AppProvider = ({ children }) => (
  <AppContext.Provider value={{ resources }}>
    {children}
  </AppContext.Provider>
);

export const useAppContext = () => useContext(AppContext);
